version: "3.7"
services:
    mysql:
        build: "./Db"
        container_name: mysql-webjump-container
        volumes:
            - ./Db/data:/var/lib/mysql
        ports: 
            - "3306:3306"
        restart: always
    web:
        build: "./App"
        container_name: php-webjump-container
        volumes:
            - ./App:/var/www/html
        ports: 
            - "80:80"
        restart: always
        depends_on: 
            - mysql